set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Generic)
set(VCPKG_CMAKE_SYSTEM_PROCESSOR wasm32)

set(CMAKE_C_COMPILER "zig" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "zig" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_TARGET "wasm32-wasi" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET "wasm32-wasi" CACHE STRING "" FORCE)
set(CMAKE_AR "zig" CACHE STRING "" FORCE)
set(CMAKE_RANLIB "zig" CACHE STRING "" FORCE)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/wasm32-wasi-toolchain.cmake")
